### ISSUE TITLE
Some notes in rare cases are silent

### ISSUE THREAD

**Issue by bryc** [8bitbubsy/ahx2play#6]
I noticed an issue in the render of this song:

https://modland.com/pub/modules/AHX/Cactoos/2%20worki%20za%20malo.ahx

In position 8 - row 32, the melody note in channel 1 is silent. 

There's another silent note at position 10 - row 32, also ch1.  Not sure if that's a coincidence.

ahx2play:

https://github.com/8bitbubsy/ahx2play/assets/1408749/db599b73-61fa-45d0-b6f3-a127b1a0d5db

WinUAE:

https://github.com/8bitbubsy/ahx2play/assets/1408749/b8b7be26-ebb8-4225-a7cc-21bc161a4cb4

AHX 2.3d-sp3 in WinUAE appears unaffected.

**Comment by bryc** [comment]
https://modland.com/pub/modules/AHX/Jazzcat/jaded%20lights.ahx

This one also appears to have a missing or 'incorrect' note, position 0, row 28.

**Comment by 8bitbubsy** [comment]
Will investigate this now. Sorry for the long delay.

**Comment by 8bitbubsy** [comment]
Ah, it's related to the 4xx command setting the filter position to a value higher than 63.
This reads out of bounds in original AHX, but for ahx2play I use a "silence" buffer in cases like this, so that it's safe.

I wonder what I should do here, really. Maybe I need to find out what comes after the filter data in AHX2.3d sp3 (68020), and include that as a buffer/table in ahx2play.

**Comment by 8bitbubsy** [comment]
> https://modland.com/pub/modules/AHX/Jazzcat/jaded%20lights.ahx
> 
> This one also appears to have a missing or 'incorrect' note, position 0, row 28.

Same problem. 4xx where xx is > $7F.

**Comment by 8bitbubsy** [comment]
I changed the behavior for this, it now clamps the filter position instead of resorting to a silenced waveform. This still doesn't make it sound identical to AHX (which is impossible since it reads outside of allocated program memory, and we don't know what's in those bytes), but at least this makes more sense.

You won't get silent notes anymore, but the filter will still not sound correct for these quirky cases.
You can achieve this through 4xx where xx is 40, or above 7F. And also through the instrument effect list.
